Repository spyder-ide/lektor-icon, pull requests merged in 2023-11, with the labels that each got.

#22 Upgrade infra, CIs and pre-commit checks & sync with website
  .browserslistrc
  .codespellrc
  .csslintrc
  .eslintrc.json
  .gitattributes
  .github/FUNDING.yml
  .github/actions/build-project/action.yml
  .github/actions/setup-and-install/action.yml
  .github/workflows/build.yaml
  .github/workflows/deploy.yml
  .github/workflows/lint.yaml
  .github/workflows/test.yml
  .gitignore
  .markdownlint.json
  .pre-commit-config.yaml
  .prettierrc.yaml
  .stylelintrc.json
  .yamllint.yml
  AUTHORS.txt
  CONTRIBUTING.md
  LICENSE.txt
  NOTICE.txt
  README.md
  SECURITY.md
  _version.txt
  assets/static/css/style.css
  assets/static/js/jquery-3.5.1.min.js
  assets/static/js/jquery-3.7.1.min.js
  assets/static/js/magnific-popup-options.js
  assets/static/js/main-singlelayout.js
  assets/static/js/main.js
  ci/build.sh
  ci/deploy.sh
  ci/install.sh
  ci/requirements-ci.txt
  example-site/README.md
  example-site/assets/static/css/example-custom-styles.css
  example-site/content/blog/lorem-ipsum/contents.lr
  example-site/content/readme/contents.lr
  example-site/lektor_icon_example.lektorproject
  netlify.toml
  requirements-dev.txt
  requirements.txt
  runtime.txt
  templates/layout.html
Labels: task

#19 Fix syntax bugs with lang tag in main template
  templates/layout.html
Labels: bug

#21 Make low hanging fruit font, layout and margin fixes
  assets/static/css/magnific-popup.css
  assets/static/css/style.css
  templates/layout.html
  templates/macros/blog.html
Labels: enhancement
